### ISSUE TITLE
Not all PHP versions found

### ISSUE THREAD

**Issue by svandragt** [svandragt/psh#8]
Yup issue with bash arrays, because who programs in bash

**Comment by tomjn** [comment]
You can list versions installed via homebrew with `brew list --versions`

Also what's the array issue? it could be the delimeter variable bash uses to determine where one item ends and the next begins

**Comment by svandragt** [comment]
Bash arrays are a pain, it's too easy to shoot yourself in the foot and lose all but the first array item or convert it to string by accident, and array items as words vs things with spaces causes problems.

Instead i'm using linebreaks and this simplified things massively. 
closed by 549af1d0597f7672a2aec540d9089c13d9f5b5fe
